name: Deploy Vite app to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: nvda-frontend
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          # no cache; no lockfile

      - name: Install deps
        run: npm install

      - name: Build
        env:
          VITE_API_BASE: ${{ secrets.VITE_API_BASE }}   # add this secret in Settings → Secrets and variables → Actions
        run: |
          echo "VITE_API_BASE=${VITE_API_BASE}" > .env.production
          npm run build -- --base="/${{ github.event.repository.name }}/"
          cp dist/index.html dist/404.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: nvda-frontend/dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
